{application,hcache,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{hcache_app,[]}},
              {env,[]},
              {modules,[conn_handler_sup,gen_nb_server,hcache,hcache_app,
                        hcache_net_listener,hcache_sup]}]}.
